In [1]:
%pip install folium

Requirement already satisfied: folium in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (0.11.0)
Requirement already satisfied: branca>=0.3.0 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from folium) (0.6.0)
Requirement already satisfied: jinja2>=2.9 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from folium) (3.1.2)
Requirement already satisfied: numpy in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from folium) (1.21.6)
Requirement already satisfied: requests in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from folium) (2.29.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from jinja2>=2.9->folium) (2.1.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from requests->folium) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from requests->folium) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from requests->folium) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from requests->folium) (2023.5.7)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import folium

In [1]:
world_map = folium.Map(location = [56.130, -106.35], zoom_start = 4)

NameError: name 'folium' is not defined

In [2]:
mexico_map = folium.Map(location = [23.6345, -102.5528], zoom_start = 4, tiles = "cartodb dark_matter", )
#mexico_map

NameError: name 'folium' is not defined

In [3]:
mexico_map_light = folium.Map(location = [23.6345, -102.5528], zoom_start = 6, tiles = "cartodb positron")
#mexico_map_light

NameError: name 'folium' is not defined

In [6]:
import requests

def download(url, filename):
    response = requests.get(url)
    try:
        if response.status_code == 200:
            print("url accesssed successfully")
            data = response.content
            with open(filename, "wb") as f:
                f.write(data)
                print("data successfully downloaded")
    except Exception as e:
        print("Error:", e)

In [7]:
url = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DV0101EN-SkillsNetwork/Data%20Files/Police_Department_Incidents_-_Previous_Year__2016_.csv'
filename = "police_data.csv"

In [8]:
download(url, filename)

url accesssed successfully
data successfully downloaded

In [9]:
df = pd.read_csv(filename)
df.head()

,IncidntNum,Category,Descript,DayOfWeek,Date,Time,PdDistrict,Resolution,Address,X,Y,Location,PdId
0,120058272,WEAPON LAWS,POSS OF PROHIBITED WEAPON,Friday,01/29/2016 12:00:00 AM,11:00,SOUTHERN,"ARREST, BOOKED",800 Block of BRYANT ST,-122.403405,37.775421,"(37.775420706711, -122.403404791479)",12005827212120
1,120058272,WEAPON LAWS,"FIREARM, LOADED, IN VEHICLE, POSSESSION OR USE",Friday,01/29/2016 12:00:00 AM,11:00,SOUTHERN,"ARREST, BOOKED",800 Block of BRYANT ST,-122.403405,37.775421,"(37.775420706711, -122.403404791479)",12005827212168
2,141059263,WARRANTS,WARRANT ARREST,Monday,04/25/2016 12:00:00 AM,14:59,BAYVIEW,"ARREST, BOOKED",KEITH ST / SHAFTER AV,-122.388856,37.729981,"(37.7299809672996, -122.388856204292)",14105926363010
3,160013662,NON-CRIMINAL,LOST PROPERTY,Tuesday,01/05/2016 12:00:00 AM,23:50,TENDERLOIN,NONE,JONES ST / OFARRELL ST,-122.412971,37.785788,"(37.7857883766888, -122.412970537591)",16001366271000
4,160002740,NON-CRIMINAL,LOST PROPERTY,Friday,01/01/2016 12:00:00 AM,00:30,MISSION,NONE,16TH ST / MISSION ST,-122.419672,37.765050,"(37.7650501214668, -122.419671780296)",16000274071000


IncidntNum: Incident Number
Category: Category of crime or incident
Descript: Description of the crime or incident
DayOfWeek: The day of week on which the incident occurred
Date: The Date on which the incident occurred
Time: The time of day on which the incident occurred
PdDistrict: The police department district
Resolution: The resolution of the crime in terms whether the perpetrator was arrested or not
Address: The closest address to where the incident took place
X: The longitude value of the crime location
Y: The latitude value of the crime location
Location: A tuple of the latitude and the longitude valuesb
PdId: The police department ID

In [10]:
df.shape

(150500, 13)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150500 entries, 0 to 150499
Data columns (total 13 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   IncidntNum  150500 non-null  int64
 1   Category    150500 non-null  object
 2   Descript    150500 non-null  object
 3   DayOfWeek   150500 non-null  object
 4   Date        150500 non-null  object
 5   Time        150500 non-null  object
 6   PdDistrict  150499 non-null  object
 7   Resolution  150500 non-null  object
 8   Address     150500 non-null  object
 9   X           150500 non-null  float64
 10  Y           150500 non-null  float64
 11  Location    150500 non-null  object
 12  PdId        150500 non-null  int64
dtypes: float64(2), int64(2), object(9)
memory usage: 14.9+ MB

<h2>San Francisco Incident Map </h2>

In [12]:
latitude = 37.77
longitude = -122.42

In [4]:
sf_map = folium.Map(location = [latitude, longitude], zoom_start = 12)
#sf_map

NameError: name 'folium' is not defined

In [5]:
df_incidents = df.head(300)

incidents = folium.map.FeatureGroup()

for lat,long in zip(df_incidents["Y"], df_incidents["X"]):
    incidents.add_child(
    folium.vector_layers.CircleMarker(
    [lat,long],
    radius = 5,
    color = "blue",
    fill = True,
    fill_color = "yellow",
    fill_opacity = .6
        )
    )
  
longitude_data = list(df_incidents["X"])
latitude_data = list(df_incidents["Y"])
labels = list(df_incidents["Category"])

for lon, lat, label in zip(longitude_data, latitude_data, labels):
    folium.Marker([lat,lon], popup = label).add_to(sf_map)

    
    
sf_map.add_child(incidents)
#sf_map

NameError: name 'df' is not defined

In [6]:
df_incidents = df.head(300)

latitude = 37.77
longitude = -122.42

sf_map = folium.Map(location = [latitude, longitude], zoom_start = 12)

incidents = folium.map.FeatureGroup()

for lat,lon,label in zip(df_incidents["Y"], df_incidents["X"], df_incidents["Category"]):
    incidents.add_child(
    folium.vector_layers.CircleMarker(
    [lat,lon],
    radius = 5,
    color = "blue",
    fill = True,
    fill_color = "yellow",
    fill_opacity = .6,
    popup = label
        )
    )
    
sf_map.add_child(incidents)
#sf_map

NameError: name 'df' is not defined

In [7]:
from folium import plugins

latitude = 37.77
longitude = -122.42

sf_map = folium.Map(location=[latitude, longitude], zoom_start = 12)

incidents_cluster = plugins.MarkerCluster().add_to(sf_map)

for lan, lon, label in zip(df["Y"], df["X"], df["Category"]):
    folium.Marker(
    location = [lan, lon],
    icon = None,
    popup = label
    ).add_to(incidents_cluster)

#sf_map

ModuleNotFoundError: No module named 'folium'

<h2>Choropleth Maps</h2>

In [34]:
df_can = pd.read_csv('https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DV0101EN-SkillsNetwork/Data%20Files/Canada.csv')

In [35]:
df_can.head()

,Country,Continent,Region,DevName,1980,1981,1982,1983,1984,1985,...,2005,2006,2007,2008,2009,2010,2011,2012,2013,Total
0,Afghanistan,Asia,Southern Asia,Developing regions,16,39,39,47,71,340,...,3436,3009,2652,2111,1746,1758,2203,2635,2004,58639
1,Albania,Europe,Southern Europe,Developed regions,1,0,0,0,0,0,...,1223,856,702,560,716,561,539,620,603,15699
2,Algeria,Africa,Northern Africa,Developing regions,80,67,71,69,63,44,...,3626,4807,3623,4005,5393,4752,4325,3774,4331,69439
3,American Samoa,Oceania,Polynesia,Developing regions,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,6
4,Andorra,Europe,Southern Europe,Developed regions,0,0,0,0,0,0,...,0,1,1,0,0,0,0,1,1,15

In [36]:
! wget --quiet https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DV0101EN-SkillsNetwork/Data%20Files/world_countries.json

In [37]:
world_geo = r'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DV0101EN-SkillsNetwork/Data%20Files/world_countries.json'

In [64]:
world_map = folium.Map(location = [0,0], zoom_start = 2)

In [53]:
import json

with open("world_countries.json", "r") as f:
    data = json.load(f)
#print(json.dumps(data, indent = 2))

In [8]:
world_map.choropleth(
    geo_data = world_geo,
    data = df_can,
    columns = ["Country", "Total"],
    key_on = "feature.properties.name",
    legend_name = "Immigration to Canada",
    fill_color = "YlOrRd",
    fill_opacity = .7,
    reset = True
)
#world_map

NameError: name 'world_map' is not defined